[package]
name = "mdpkm"
version = "2.0.0-beta.1"
description = "A Tauri App"
authors = ["Blookers"]
license = ""
repository = ""
default-run = "mdpkm"
edition = "2021"
rust-version = "1.61"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.0", features = [] }

[dependencies]
serde_json = "1.0"
sysinfo = "0.26.7"
reqwest = "0.11.10"
windows = { version = "0.35.0", features = ["System", "Storage", "Management_Deployment", "ApplicationModel", "Foundation", "Foundation_Collections", "Security_Authentication_Web_Core", "Security_Credentials"] }
walkdir = "2.3.2"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2.0", features = ["clipboard-write-text", "dialog-open", "dialog-save", "fs-all", "http-multipart", "http-request", "os-all", "path-all", "process-exit", "protocol-asset", "shell-open", "updater", "window-close", "window-create", "window-maximize", "window-minimize", "window-set-focus", "window-start-dragging", "window-unmaximize"] }
rand = "0.8.5"
zip = "0.6.3"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
