[package]
name = "mdpkm"
version = "1.7.0"
description = "A Tauri App"
authors = ["Blookers"]
license = ""
repository = ""
default-run = "mdpkm"
edition = "2021"
rust-version = "1.61"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.4", features = [] }

[dependencies]
events_emitter = "0.1.3"
snailquote = "0.3.1"
serde_json = "1.0"
crc32fast = "1.3.2"
sysinfo = "0.23.13"
reqwest = "0.11.10"
windows = { version = "0.35.0", features = ["System", "Storage", "Management_Deployment", "ApplicationModel", "Foundation", "Foundation_Collections", "Security_Authentication_Web_Core", "Security_Credentials"] }
walkdir = "2.3.2"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.5", features = ["clipboard-write-text", "dialog-open", "dialog-save", "http-multipart", "http-request", "os-all", "path-all", "process-exit", "process-relaunch", "protocol-asset", "shell-open", "updater", "window-close", "window-create", "window-maximize", "window-minimize", "window-set-focus", "window-start-dragging", "window-unmaximize"] }
rand = "0.8.5"
url = "2.2.2"
zip = "0.5"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
