name: 'build'
on:
  push:
    branches:
      - master

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install voxura dependencies
        run: cd voxura && yarn
      - name: install voxeliface dependencies
        run: cd voxeliface && yarn
      - name: install app dependencies and build it
        run: yarn && yarn vite build
      - uses: tauri-apps/tauri-action@v0
        with:
          includeDebug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v2
        if: matrix.platform == 'ubuntu-20.04'
        with:
            name: mdpkm-linux-debug.deb
            path: src-tauri/target/debug/bundle/deb/*.deb
            if-no-files-found: error
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v2
        if: matrix.platform == 'windows-latest'
        with:
            name: mdpkm-windows-debug.msi
            path: src-tauri/target/debug/bundle/msi/*.msi
            if-no-files-found: error
